language: node_js
node_js:
- '6'
install:
- npm install
deploy:
  skip_cleanup: true
  provider: npm
  email: bradwoo8621@gmail.com
  api_key:
    secure: fzjafZd9wP+wkzAFRlkTdMpoiMjG6VRz5KljlcW8qvdtZC9gRexsmSTANyCC2bH+zYrdWlyOP+3lsJuIaxI1M/O0fgcZj/5KSbHieXIzO2cM3qUv/iTaGldlsogdytE/a7hOm1i7nEdHv8RZebhAx16bz2OgZpjxKfBnlTKshqI3QYxr8ExOhP+tHRiN3Rpk8ICKuepoHcJZ6idwnpKv8v7H+BuNbl3C4C3R13wxyLjDObU6eX0LD65u1mnsoY9wURTHn0snYnot2Wm5409cp4BIiQRkVvgj9Z5eDvGKi5VC+TnNyrCqxvQTThviqb2riHZ8OslecDejP3KUDEEH3dYgtqAOnHaknGU0sGxXuJxXSoVIATap5qm1Hl3ENDLgmQEO9Ko0jocs0oieziQE5SPg1YHQLILHv0DmX9RhfljTa+TLpBwhUeHSqYpm0xnGcwe56CTK2OR5EjVurZ/LYYHsQZKedinHlje/QlJndAmZkGypsqzKNYHEVt7JJ/k+8LeohfZGietlp/Ah6dL6AGrB3RPG0c+qXp/cjjfYUrj7NR9cvIQulXeX/ASL5kU7wubPBUAV/FybLDT7gJ4rkTFE5iKW85uo0WVkSJBRydHiCfwb6CKTG0EVHhedwZglErfJ0ozfT6pZ6OXKCCaQTXaq4+bvUJCnnd9uoh4UVsM=
  on:
    tags: true
